# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:08:02+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Bin(BaseModel):
    density: Optional[float] = Field(
        None,
        description="The proportion of users that experienced this bin's value for the given metric.",
    )
    end: Optional[Any] = Field(
        None,
        description='End is the end of the data bin. If end is not populated, then the bin has no end and is valid from start to +inf.',
    )
    start: Optional[Any] = Field(
        None, description='Start is the beginning of the data bin.'
    )


class Date(BaseModel):
    day: Optional[int] = Field(
        None,
        description="Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
    )
    month: Optional[int] = Field(
        None,
        description='Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.',
    )
    year: Optional[int] = Field(
        None,
        description='Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.',
    )


class FormFactor(Enum):
    ALL_FORM_FACTORS = 'ALL_FORM_FACTORS'
    PHONE = 'PHONE'
    DESKTOP = 'DESKTOP'
    TABLET = 'TABLET'


class HistoryKey(BaseModel):
    formFactor: Optional[FormFactor] = Field(
        None,
        description='The form factor is the device class that all users used to access the site for this record. If the form factor is unspecified, then aggregated data over all form factors will be returned.',
    )
    origin: Optional[str] = Field(
        None,
        description='Origin specifies the origin that this record is for. Note: When specifying an origin, data for loads under this origin over all pages are aggregated into origin level user experience data.',
    )
    url: Optional[str] = Field(
        None,
        description='Url specifies a specific url that this record is for. This url should be normalized, following the normalization actions taken in the request to increase the chances of successful lookup. Note: When specifying a "url" only data for that specific url will be aggregated.',
    )


class Key(BaseModel):
    effectiveConnectionType: Optional[str] = Field(
        None,
        description='The effective connection type is the general connection class that all users experienced for this record. This field uses the values ["offline", "slow-2G", "2G", "3G", "4G"] as specified in: https://wicg.github.io/netinfo/#effective-connection-types If the effective connection type is unspecified, then aggregated data over all effective connection types will be returned.',
    )
    formFactor: Optional[FormFactor] = Field(
        None,
        description='The form factor is the device class that all users used to access the site for this record. If the form factor is unspecified, then aggregated data over all form factors will be returned.',
    )
    origin: Optional[str] = Field(
        None,
        description='Origin specifies the origin that this record is for. Note: When specifying an origin, data for loads under this origin over all pages are aggregated into origin level user experience data.',
    )
    url: Optional[str] = Field(
        None,
        description='Url specifies a specific url that this record is for. Note: When specifying a "url" only data for that specific url will be aggregated.',
    )


class Percentiles(BaseModel):
    p75: Optional[Any] = Field(
        None,
        description='75% of users experienced the given metric at or below this value.',
    )


class QueryHistoryRequest(BaseModel):
    formFactor: Optional[FormFactor] = Field(
        None,
        description="The form factor is a query dimension that specifies the device class that the record's data should belong to. Note: If no form factor is specified, then a special record with aggregated data over all form factors will be returned.",
    )
    metrics: Optional[List[str]] = Field(
        None,
        description='The metrics that should be included in the response. If none are specified then any metrics found will be returned. Allowed values: ["first_contentful_paint", "first_input_delay", "largest_contentful_paint", "cumulative_layout_shift", "experimental_time_to_first_byte", "experimental_interaction_to_next_paint"]',
    )
    origin: Optional[str] = Field(
        None,
        description='The url pattern "origin" refers to a url pattern that is the origin of a website. Examples: "https://example.com", "https://cloud.google.com"',
    )
    url: Optional[str] = Field(
        None,
        description='The url pattern "url" refers to a url pattern that is any arbitrary url. Examples: "https://example.com/", "https://cloud.google.com/why-google-cloud/"',
    )


class QueryRequest(BaseModel):
    effectiveConnectionType: Optional[str] = Field(
        None,
        description='The effective connection type is a query dimension that specifies the effective network class that the record\'s data should belong to. This field uses the values ["offline", "slow-2G", "2G", "3G", "4G"] as specified in: https://wicg.github.io/netinfo/#effective-connection-types Note: If no effective connection type is specified, then a special record with aggregated data over all effective connection types will be returned.',
    )
    formFactor: Optional[FormFactor] = Field(
        None,
        description="The form factor is a query dimension that specifies the device class that the record's data should belong to. Note: If no form factor is specified, then a special record with aggregated data over all form factors will be returned.",
    )
    metrics: Optional[List[str]] = Field(
        None,
        description='The metrics that should be included in the response. If none are specified then any metrics found will be returned. Allowed values: ["first_contentful_paint", "first_input_delay", "largest_contentful_paint", "cumulative_layout_shift", "experimental_time_to_first_byte", "experimental_interaction_to_next_paint"]',
    )
    origin: Optional[str] = Field(
        None,
        description='The url pattern "origin" refers to a url pattern that is the origin of a website. Examples: "https://example.com", "https://cloud.google.com"',
    )
    url: Optional[str] = Field(
        None,
        description='The url pattern "url" refers to a url pattern that is any arbitrary url. Examples: "https://example.com/", "https://cloud.google.com/why-google-cloud/"',
    )


class TimeseriesBin(BaseModel):
    densities: Optional[List[float]] = Field(
        None,
        description="The proportion of users that experienced this bin's value for the given metric in a given collection period; the index for each of these entries corresponds to an entry in the CollectionPeriods field in the HistoryRecord message, which describes when the density was observed in the field. Thus, the length of this list of densities is equal to the length of the CollectionPeriods field in the HistoryRecord message.",
    )
    end: Optional[Any] = Field(
        None,
        description='End is the end of the data bin. If end is not populated, then the bin has no end and is valid from start to +inf.',
    )
    start: Optional[Any] = Field(
        None, description='Start is the beginning of the data bin.'
    )


class TimeseriesPercentiles(BaseModel):
    p75s: Optional[List] = Field(
        None,
        description='75% of users experienced the given metric at or below this value. The length of this list of densities is equal to the length of the CollectionPeriods field in the HistoryRecord message, which describes when the density was observed in the field.',
    )


class UrlNormalization(BaseModel):
    normalizedUrl: Optional[str] = Field(
        None,
        description='The URL after any normalization actions. This is a valid user experience URL that could reasonably be looked up.',
    )
    originalUrl: Optional[str] = Field(
        None,
        description='The original requested URL prior to any normalization actions.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class CollectionPeriod(BaseModel):
    firstDate: Optional[Date] = Field(
        None, description='The first day in the collection period, inclusive.'
    )
    lastDate: Optional[Date] = Field(
        None, description='The last day in the collection period, inclusive.'
    )


class Metric(BaseModel):
    histogram: Optional[List[Bin]] = Field(
        None,
        description='The histogram of user experiences for a metric. The histogram will have at least one bin and the densities of all bins will add up to ~1.',
    )
    percentiles: Optional[Percentiles] = Field(
        None,
        description='Commonly useful percentiles of the Metric. The value type for the percentiles will be the same as the value types given for the Histogram bins.',
    )


class MetricTimeseries(BaseModel):
    histogramTimeseries: Optional[List[TimeseriesBin]] = Field(
        None,
        description='The histogram of user experiences for a metric. The histogram will have at least one bin and the densities of all bins will add up to ~1, for each timeseries entry.',
    )
    percentilesTimeseries: Optional[TimeseriesPercentiles] = Field(
        None,
        description='Commonly useful percentiles of the Metric. The value type for the percentiles will be the same as the value types given for the Histogram bins.',
    )


class Record(BaseModel):
    collectionPeriod: Optional[CollectionPeriod] = Field(
        None,
        description='The collection period indicates when the data reflected in this record was collected.',
    )
    key: Optional[Key] = Field(
        None,
        description='Key defines all of the unique querying parameters needed to look up a user experience record.',
    )
    metrics: Optional[Dict[str, Metric]] = Field(
        None,
        description='Metrics is the map of user experience data available for the record defined in the key field. Metrics are keyed on the metric name. Allowed key values: ["first_contentful_paint", "first_input_delay", "largest_contentful_paint", "cumulative_layout_shift", "experimental_time_to_first_byte", "experimental_interaction_to_next_paint"]',
    )


class HistoryRecord(BaseModel):
    collectionPeriods: Optional[List[CollectionPeriod]] = Field(
        None,
        description='The collection periods indicate when each of the data points reflected in the time series data in metrics was collected. Note that all the time series share the same collection periods, and it is enforced in the CrUX pipeline that every time series has the same number of data points.',
    )
    key: Optional[HistoryKey] = Field(
        None,
        description='Key defines all of the unique querying parameters needed to look up a user experience history record.',
    )
    metrics: Optional[Dict[str, MetricTimeseries]] = Field(
        None,
        description='Metrics is the map of user experience time series data available for the record defined in the key field. Metrics are keyed on the metric name. Allowed key values: ["first_contentful_paint", "first_input_delay", "largest_contentful_paint", "cumulative_layout_shift", "experimental_time_to_first_byte", "experimental_interaction_to_next_paint"]',
    )


class QueryHistoryResponse(BaseModel):
    record: Optional[HistoryRecord] = Field(
        None, description='The record that was found.'
    )
    urlNormalizationDetails: Optional[UrlNormalization] = Field(
        None,
        description='These are details about automated normalization actions that were taken in order to make the requested `url_pattern` valid.',
    )


class QueryResponse(BaseModel):
    record: Optional[Record] = Field(None, description='The record that was found.')
    urlNormalizationDetails: Optional[UrlNormalization] = Field(
        None,
        description='These are details about automated normalization actions that were taken in order to make the requested `url_pattern` valid.',
    )
